/* Generated By:JJTree&JavaCC: Do not edit this line. ExampleParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int COMP = 8;
  /** RegularExpression Id. */
  int PROP = 9;
  /** RegularExpression Id. */
  int EVT = 10;
  /** RegularExpression Id. */
  int ACTIONS = 11;
  /** RegularExpression Id. */
  int INITIALISATIONS = 12;
  /** RegularExpression Id. */
  int INTERFACE = 13;
  /** RegularExpression Id. */
  int DEBUT = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int FIN = 18;
  /** RegularExpression Id. */
  int TYPEv = 19;
  /** RegularExpression Id. */
  int TypeC = 20;
  /** RegularExpression Id. */
  int TypeA = 21;
  /** RegularExpression Id. */
  int TypeFen = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;
  /** RegularExpression Id. */
  int LETTER = 24;
  /** RegularExpression Id. */
  int Tpoint = 25;
  /** RegularExpression Id. */
  int PV = 26;
  /** RegularExpression Id. */
  int AFF = 27;
  /** RegularExpression Id. */
  int VR = 28;
  /** RegularExpression Id. */
  int compare = 29;
  /** RegularExpression Id. */
  int plus = 30;
  /** RegularExpression Id. */
  int minus = 31;
  /** RegularExpression Id. */
  int op2 = 32;
  /** RegularExpression Id. */
  int opA = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<NUMBER>",
    "<DIGIT>",
    "\"COMP\"",
    "\"PROP\"",
    "<EVT>",
    "\"ACTIONS\"",
    "\"INITIALISATIONS\"",
    "\"INTERFACE\"",
    "\"DEBUT\"",
    "\"If\"",
    "\"Then\"",
    "\"and\"",
    "\"FIN\"",
    "<TYPEv>",
    "<TypeC>",
    "<TypeA>",
    "<TypeFen>",
    "<IDENTIFIER>",
    "<LETTER>",
    "\":\"",
    "\";\"",
    "\":=\"",
    "\",\"",
    "<compare>",
    "\"+\"",
    "\"-\"",
    "<op2>",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
