/* Generated By:JavaCC: Do not edit this line. ExampleParserVisitor.java Version 5.0 */
public interface ExampleParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTcommence node, Object data);
  public Object visit(ASTstart node, Object data);
  public Object visit(ASTcomp node, Object data);
  public Object visit(ASTprop node, Object data);
  public Object visit(ASTlistV node, Object data);
  public Object visit(ASTvar node, Object data);
  public Object visit(ASTenu node, Object data);
  public Object visit(ASTlv node, Object data);
  public Object visit(ASTevt node, Object data);
  public Object visit(ASTlistE node, Object data);
  public Object visit(ASTifstmt node, Object data);
  public Object visit(ASTaffect node, Object data);
  public Object visit(ASTexpr node, Object data);
  public Object visit(ASTcond node, Object data);
  public Object visit(ASTterme node, Object data);
  public Object visit(ASTfacteur node, Object data);
  public Object visit(ASTinit node, Object data);
  public Object visit(ASTaction node, Object data);
}
/* JavaCC - OriginalChecksum=3176200a5392b5df51899f73e9ed64ba (do not edit this line) */
