/* Generated By:JavaCC: Do not edit this line. ExampleParserTreeConstants.java Version 5.0 */
public interface ExampleParserTreeConstants
{
  public int JJTCOMMENCE = 0;
  public int JJTSTART = 1;
  public int JJTCOMP = 2;
  public int JJTPROP = 3;
  public int JJTLISTV = 4;
  public int JJTVAR = 5;
  public int JJTENU = 6;
  public int JJTLV = 7;
  public int JJTEVT = 8;
  public int JJTLISTE = 9;
  public int JJTIFSTMT = 10;
  public int JJTAFFECT = 11;
  public int JJTEXPR = 12;
  public int JJTCOND = 13;
  public int JJTTERME = 14;
  public int JJTFACTEUR = 15;
  public int JJTINIT = 16;
  public int JJTACTION = 17;


  public String[] jjtNodeName = {
    "commence",
    "start",
    "comp",
    "prop",
    "listV",
    "var",
    "enu",
    "lv",
    "evt",
    "listE",
    "ifstmt",
    "affect",
    "expr",
    "cond",
    "terme",
    "facteur",
    "init",
    "action",
  };
}
/* JavaCC - OriginalChecksum=4916fdc1f1d8bf4529b180417457b3b3 (do not edit this line) */
